### ISSUE TITLE
Installation Created: event triggers a NullPointerException

### ISSUE THREAD

**Issue by gsmachado** [quarkiverse/quarkus-github-app#253]
Before: this extension is absolutely great! Pretty much liked it! Congrats! 👍 🎉 

Now, let me get to the issue:

I tried to get a `Installation.Created` event, but then I stumbled across the following exception:

```
Exception: java.lang.NullPointerException: Missing instance URL!
	at java.base/java.util.Objects.requireNonNull(Objects.java:247)
	at org.kohsuke.github.GHRepository.populate(GHRepository.java:3260)
	at org.kohsuke.github.GHEventPayload$Installation.lateBind(GHEventPayload.java:276)
	at org.kohsuke.github.GitHub.parseEventPayload(GitHub.java:944)
	at io.quarkiverse.githubapp.GitHubEventDispatcherImpl.dispatch(Unknown Source)
	at io.quarkiverse.githubapp.GitHubEventDispatcherImpl_Subclass.dispatch$$superforward1(Unknown Source)
	at io.quarkiverse.githubapp.GitHubEventDispatcherImpl_Subclass$$function$$1.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.quarkiverse.githubapp.GitHubEventDispatcherImpl_Subclass.dispatch(Unknown Source)
	at io.quarkiverse.githubapp.GitHubEventDispatcherImpl_Observer_dispatch_2d7663abb168c3cf472f4244f593b64c986877c4.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:320)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:298)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:73)
	at io.quarkiverse.githubapp.runtime.Routes.handleRequest(Routes.java:128)
	at io.quarkiverse.githubapp.runtime.Routes_Subclass.handleRequest$$superforward1(Unknown Source)
	at io.quarkiverse.githubapp.runtime.Routes_Subclass$$function$$1.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.quarkiverse.githubapp.runtime.Routes_Subclass.handleRequest(Unknown Source)
	at io.quarkiverse.githubapp.runtime.Routes_RouteHandler_handleRequest_516ab5af9409426c5dbdf44ccd172a61ce906df9.invoke(Unknown Source)
	at io.quarkus.vertx.web.runtime.RouteHandler.handle(RouteHandler.java:97)
	at io.quarkus.vertx.web.runtime.RouteHandler.handle(RouteHandler.java:22)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

This is most likely happening when trying to populate data from the GitHub repositories JSON object:

![image](https://user-images.githubusercontent.com/2124276/152143575-a8665522-5dc3-42f3-89ff-2a8cb5006f5a.png)

Maybe it doesn't find the `url` JSON attribute and then it breaks on this line:

![image](https://user-images.githubusercontent.com/2124276/152143720-5600c989-be39-4816-9418-717ccf20a6fd.png)

Is there a workaround for this? Maybe a config to avoid this problem?

**Comment by gsmet** [comment]
Any chance you could share the payload with me (as text)?

You can anonymize the sensitive information, it's more about having the structure of it so that I can have a look at what the Hub4j GitHub API is doing.

**Comment by gsmet** [comment]
I suspect the repository data included in the payload is incomplete and doesn't allow to create a `GHRepository`. If you can get me the payload triggering the issue, I'll have a closer look today.

**Comment by gsmet** [comment]
Hmmm, no need for the payload, we have an example in the tests here: https://github.com/hub4j/github-api/blob/main/src/test/resources/org/kohsuke/github/GHEventPayloadTest/installation.json#L45-L53 .

Trying to understand why the tests pass with this. Probably because in the GitHub API tests, the tests are done in offline mode.

**Comment by gsmet** [comment]
@gsmachado could you try this PR: https://github.com/hub4j/github-api/pull/1371 ?

It's a PR for github-api so you should build it locally (`mvn clean install -DskipTests`) then override the version with `1.302-SNAPSHOT` in your GitHub App project `pom.xml`:
```
<dependency>
    <groupId>org.kohsuke</groupId>
    <artifactId>github-api</artifactId>
    <version>1.302-SNAPSHOT</version>
</dependency>
```

Let me know how it goes.

**Comment by gsmachado** [comment]
@gsmet sorry for my late reply, but yes, awesome that you already took a look at it!

I will try later today and get back to you! 👍 💯

**Comment by gsmet** [comment]
@gsmachado thanks for confirming. I'll see with Liam from the GitHub API project how we can make progress on this. I'll keep you posted.

**Comment by gsmet** [comment]
And don't hesitate if you have any other issues or suggestions. As you can see, we like it :).

**Comment by gsmachado** [comment]
> And don't hesitate if you have any other issues or suggestions. As you can see, we like it :).

Great to know! 

We, @AxLabs, are just starting the development of a GitHub App which will be used in a relatively large community. For the first time we're trying the combination of quarkus + quarkus-github-app, and so far we like it.

Let's leave this issue open until https://github.com/hub4j/github-api/pull/1371 gets merged. 👍

**Comment by gsmet** [comment]
@gsmachado I just released 1.7.1 with the GitHub API upgrade. It is available on Maven Central.

**Comment by gsmachado** [comment]
@gsmet awesome! thanks!
