### ISSUE TITLE
AbstractMethodError

### ISSUE THREAD

**Issue by tombentley** [quarkiverse/quarkus-github-app#273]
After following the great documentation, I wrote a method like this

```java
    void onComment(@IssueComment GHEventPayload.IssueComment commentPayload, GitHub client) throws IOException {
        GHTeam team = client.getOrganization("foo").getTeamByName("bar");
        String body = commentPayload.getComment().getBody();
        if (body.startsWith("/baz")
                && commentPayload.getComment().getUser().isMemberOf(team)) {
            commentPayload.getComment().createReaction(ReactionContent.PLUS_ONE);
        }
    }
```

which yielded this stacktrace

```
java.lang.RuntimeException: Error checking value of member method value on interface io.quarkiverse.githubapp.event.IssueComment
	at javax.enterprise.util.AnnotationLiteral.invoke(AnnotationLiteral.java:291)
	at javax.enterprise.util.AnnotationLiteral.getMemberValue(AnnotationLiteral.java:276)
	at javax.enterprise.util.AnnotationLiteral.hashCode(AnnotationLiteral.java:246)
	at java.base/java.util.HashMap.hash(HashMap.java:340)
	at java.base/java.util.HashMap.put(HashMap.java:608)
	at java.base/java.util.HashSet.add(HashSet.java:220)
	at java.base/java.util.Collections.addAll(Collections.java:5506)
	at io.quarkus.arc.impl.EventImpl.select(EventImpl.java:123)
	at io.quarkiverse.githubapp.GitHubEventDispatcherImpl.dispatch(Unknown Source)
	at io.quarkiverse.githubapp.GitHubEventDispatcherImpl_Subclass.dispatch$$superforward1(Unknown Source)
	at io.quarkiverse.githubapp.GitHubEventDispatcherImpl_Subclass$$function$$1.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.quarkiverse.githubapp.GitHubEventDispatcherImpl_Subclass.dispatch(Unknown Source)
	at io.quarkiverse.githubapp.GitHubEventDispatcherImpl_Observer_dispatch_10cbdb5d916a1d0c73e9b215310e5498da0bbaad.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:320)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:298)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:73)
	at io.quarkiverse.githubapp.runtime.Routes.handleRequest(Routes.java:128)
	at io.quarkiverse.githubapp.runtime.Routes_Subclass.handleRequest$$superforward1(Unknown Source)
	at io.quarkiverse.githubapp.runtime.Routes_Subclass$$function$$2.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.quarkiverse.githubapp.runtime.Routes_Subclass.handleRequest(Unknown Source)
	at io.quarkiverse.githubapp.runtime.Routes_RouteHandler_handleRequest_516ab5af9409426c5dbdf44ccd172a61ce906df9.invoke(Unknown Source)
	at io.quarkus.vertx.web.runtime.RouteHandler.handle(RouteHandler.java:97)
	at io.quarkus.vertx.web.runtime.RouteHandler.handle(RouteHandler.java:22)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at javax.enterprise.util.AnnotationLiteral.invoke(AnnotationLiteral.java:288)
	... 47 more
Caused by: java.lang.AbstractMethodError: Receiver class io.quarkiverse.githubapp.event.IssueComment_AnnotationLiteral does not define or inherit an implementation of the resolved method 'abstract java.lang.String value()' of interface io.quarkiverse.githubapp.event.IssueComment.
	... 52 more
```

**Comment by gsmet** [comment]
Hey Tom,

Looks like there's an issue with catch all annotations, which I never used and apparently we don't have a test for them... I'll have a look later today.
For now, as a workaround, you can use the more precise event annotations:
```java
    void onComment(@IssueComment.Created @IssueComment.Edited GHEventPayload.IssueComment commentPayload, GitHub client) throws IOException {
        GHTeam team = client.getOrganization("foo").getTeamByName("bar");
        String body = commentPayload.getComment().getBody();
        if (body.startsWith("/baz")
                && commentPayload.getComment().getUser().isMemberOf(team)) {
            commentPayload.getComment().createReaction(ReactionContent.PLUS_ONE);
        }
    }
```

**Comment by gsmet** [comment]
And in your case, I think it makes more sense anyway as you probably don't want to listen to the `Deleted` event.

**Comment by tombentley** [comment]
Great, thanks @gsmet!
