### ISSUE TITLE
`org.kohsuke.github.GHPullRequest$AutoMerge` does not seem to be properly added to the native build

### ISSUE THREAD

**Issue by scholzj** [quarkiverse/quarkus-github-app#277]
When the application is using native build and tries to work with a PR which has the _Auto Merge_ feature enabled, it failes to deserialize the PR:

```
Exception: java.util.concurrent.CompletionException: org.kohsuke.github.HttpException: Server returned HTTP response code: 200, message: 'null' for URL: https://api.github.com/repos/scholzj/test-repo/pulls/13
	at io.quarkus.arc.impl.EventImpl.handleExceptions(EventImpl.java:205)
	at io.quarkus.arc.impl.EventImpl$1.get(EventImpl.java:102)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:829)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: org.kohsuke.github.HttpException: Server returned HTTP response code: 200, message: 'null' for URL: https://api.github.com/repos/scholzj/test-repo/pulls/13
	at org.kohsuke.github.GitHubClient.interpretApiError(GitHubClient.java:548)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:401)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:355)
	at org.kohsuke.github.Requester.fetch(Requester.java:76)
	at org.kohsuke.github.GHRepository.getPullRequest(GHRepository.java:1504)
	at cz.scholz.milestonecheck.MilestoneCheck.onIssue(MilestoneCheck.java:35)
	at cz.scholz.milestonecheck.MilestoneCheck_Multiplexer.onIssue_b81ad9dedcc11b629dc5c57b612dce49f275822b(Unknown Source)
	at cz.scholz.milestonecheck.MilestoneCheck_Multiplexer_Observer_onIssue_b81ad9dedcc11b629dc5c57b612dce49f275822b_8bddb47cb393d69610f6304049ad502bf5a86680.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:320)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:302)
	at io.quarkus.arc.impl.EventImpl$1.get(EventImpl.java:101)
	... 10 more
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.kohsuke.github.GHPullRequest$AutoMerge` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (String)"{"url":"https://api.github.com/repos/scholzj/test-repo/pulls/13","id":905219516,"node_id":"PR_kwDOCcuZqM419I28","html_url":"https://github.com/scholzj/test-repo/pull/13","diff_url":"https://github.com/scholzj/test-repo/pull/13.diff","patch_url":"https://github.com/scholzj/test-repo/pull/13.patch","issue_url":"https://api.github.com/repos/scholzj/test-repo/issues/13","number":13,"state":"open","locked":false,"title":"Update README.md","user":{"login":"scholzj","id":5658439,"node_id":"MDQ6VXNlcjU2"[truncated 15221 chars]; line: 1, column: 14488] (through reference chain: org.kohsuke.github.GHPullRequest["auto_merge"])
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1904)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1349)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1415)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:351)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:184)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:391)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:184)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2051)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1492)
	at org.kohsuke.github.GitHubResponse.parseBody(GitHubResponse.java:88)
	at org.kohsuke.github.Requester.lambda$fetch$1(Requester.java:76)
	at org.kohsuke.github.GitHubClient.createResponse(GitHubClient.java:485)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:387)
	... 19 more
```

This seems to be because the `org.kohsuke.github.GHPullRequest$AutoMerge` class is not properly added to the native build (everything seems to work fine when not using the native build).

I was able to workaround the issue by adding this class through the `ReflectionConfigurationFiles` option. But I wonder if this is something what should be set by default and work out of the box.

**Comment by gsmet** [comment]
Thanks for the report. I somehow missed it when I added all of them to https://github.com/quarkiverse/quarkus-github-api .
I released 1.303.1 of quarkus-github-api. Will upgrade quarkus-github-app once it hits Central.

**Comment by scholzj** [comment]
Ha, I wondered where it is configured when I didn't found anything in this repo. But didn't realized there was another project for the GitHub API 🤦 . Thanks for fixing it.

**Comment by gsmet** [comment]
1.8.0 has hit Central with the fix.

It also comes with a nice new feature: easy comment-based command development using Airline. It's an additional extension `quarkus-github-app-command-airline`.
I still need to work on the documentation, I'll do that this week in the evenings.
