### ISSUE TITLE
Not all parsing errors can be outputted as comments

### ISSUE THREAD

**Issue by lppedd** [quarkiverse/quarkus-github-app#366]
Let's say I get this exception:
```
Exception: java.lang.IllegalArgumentException: unbalanced quotes in @bot git cherry-pick -to "my-bran" c"
	at io.quarkiverse.githubapp.command.airline.runtime.util.Commandline.translateCommandline(Commandline.java:98)
	at io.quarkiverse.githubapp.command.airline.runtime.AbstractCommandDispatcher.getCommand(AbstractCommandDispatcher.java:73)
	at com.lppedd.app.commands.AppCliCommandDispatcherImpl.dispatch(Unknown Source)
	at com.lppedd.app.commands.AppCliCommandDispatcherImpl_Multiplexer_Subclass.dispatch$$superforward1(Unknown Source)
	at com.lppedd.app.commands.AppCliCommandDispatcherImpl_Multiplexer_Subclass$$function$$8.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
```

The error goes through `DefaultErrorHandler`, and it's simply logged.
Is there a way to allow a custom error handler to reply to the issue/PR with the error message?

**Comment by lppedd** [comment]
Oh ok, I'm un dumb mode today.

`handleError` has a `GHEventPayload` parameter, which can be a `GHEventPayload.IssueComment`.  
Then, for example, simply:

```kotlin
@ApplicationScoped
class AppErrorHandler(private val defaultErrorHandler: DefaultErrorHandler) : ErrorHandler {
  override fun handleError(gitHubEvent: GitHubEvent, payload: GHEventPayload?, throwable: Throwable?) {
    defaultErrorHandler.handleError(gitHubEvent, payload, throwable)

    if (payload is GHEventPayload.IssueComment) {
      val issue = payload.issue
      issue.comment(throwable?.message ?: "Unknown error")
    }
  }
}
```

**Comment by gsmet** [comment]
I think we should handle it on the Quarkus GitHub App side.

**Comment by lppedd** [comment]
@gsmet there is another issue with the above approach. I get an infinite loop when I reply.

**Comment by gsmet** [comment]
Do you have a listener on IssueComment?

**Comment by gsmet** [comment]
Well, a stacktrace would probably help :)

**Comment by lppedd** [comment]
@gsmet nope. This example does not cause the infinite loop.
```
override fun handleError(gitHubEvent: GitHubEvent, payload: GHEventPayload?, throwable: Throwable) {
  defaultErrorHandler.handleError(gitHubEvent, payload, throwable)
  if (payload is GHEventPayload.IssueComment) {
    val issue = payload.issue
    issue.comment("Example")
  }
}
```

While this does:
```
override fun handleError(gitHubEvent: GitHubEvent, payload: GHEventPayload?, throwable: Throwable) {
  defaultErrorHandler.handleError(gitHubEvent, payload, throwable)
  if (payload is GHEventPayload.IssueComment) {
    val issue = payload.issue
    val comment = payload.comment
    val message = throwable.message ?: "Unknown error"
    val reply = ":rotating_light: ${safeMessage(message, comment.body)}" // :rotating_light: unbalanced quotes in `:rotating_light: unbalanced quotes in `git cherry-pick -to "my-branc" h"``
    issue.comment(reply)
  }
}

private fun safeMessage(message: String, command: String): String {
  val replace = command.replace(Regex("@(ce)?bot"), "").trim()
  return message.replace(command, "`$replace`")
}
```

**Comment by lppedd** [comment]
The stacktrace is the following. Although it's always the same every iteration.

```
handleError:14, AppErrorHandler (com.lppedd.app)
handleError$$superforward1:-1, AppErrorHandler_Subclass (com.lppedd.app)
apply:-1, AppErrorHandler_Subclass$$function$$2 (com.lppedd.app)
proceed:53, AroundInvokeInvocationContext (io.quarkus.arc.impl)
proceed:62, InvocationInterceptor (io.quarkus.arc.runtime.devconsole)
monitor:49, InvocationInterceptor (io.quarkus.arc.runtime.devconsole)
intercept:-1, InvocationInterceptor_Bean (io.quarkus.arc.runtime.devconsole)
invoke:41, InterceptorInvocation (io.quarkus.arc.impl)
perform:40, AroundInvokeInvocationContext (io.quarkus.arc.impl)
performAroundInvoke:32, InvocationContexts (io.quarkus.arc.impl)
handleError:-1, AppErrorHandler_Subclass (com.lppedd.app)
handleError:-1, AppErrorHandler_ClientProxy (com.lppedd.app)
dispatch_9c21b751bd1c3c76c9e9f8d4cbcacbc05e9e7ed7:-1, AppCliCommandDispatcherImpl_Multiplexer (com.lppedd.app.commands)
dispatch_9c21b751bd1c3c76c9e9f8d4cbcacbc05e9e7ed7$$superforward1:-1, AppCliCommandDispatcherImpl_Multiplexer_Subclass (com.lppedd.app.commands)
apply:-1, AppCliCommandDispatcherImpl_Multiplexer_Subclass$$function$$9 (com.lppedd.app.commands)
proceed:53, AroundInvokeInvocationContext (io.quarkus.arc.impl)
proceed:62, InvocationInterceptor (io.quarkus.arc.runtime.devconsole)
monitor:49, InvocationInterceptor (io.quarkus.arc.runtime.devconsole)
intercept:-1, InvocationInterceptor_Bean (io.quarkus.arc.runtime.devconsole)
invoke:41, InterceptorInvocation (io.quarkus.arc.impl)
perform:40, AroundInvokeInvocationContext (io.quarkus.arc.impl)
performAroundInvoke:32, InvocationContexts (io.quarkus.arc.impl)
dispatch_9c21b751bd1c3c76c9e9f8d4cbcacbc05e9e7ed7:-1, AppCliCommandDispatcherImpl_Multiplexer_Subclass (com.lppedd.app.commands)
notify:-1, AppCliCommandDispatcherImpl_Multiplexer_Observer_dispatch_9c21b751bd1c3c76c9e9f8d4cbcacbc05e9e7ed7_2356521917b62bc538514972c7acf4a839e3d88d (com.lppedd.app.commands)
notifyObservers:323, EventImpl$Notifier (io.quarkus.arc.impl)
notify:305, EventImpl$Notifier (io.quarkus.arc.impl)
get:103, EventImpl$1 (io.quarkus.arc.impl)
run:1700, CompletableFuture$AsyncSupply (java.util.concurrent)
runWith:557, VertxCoreRecorder$14 (io.quarkus.vertx.core.runtime)
run:2449, EnhancedQueueExecutor$Task (org.jboss.threads)
run:1478, EnhancedQueueExecutor$ThreadBody (org.jboss.threads)
run:29, DelegatingRunnable (org.jboss.threads)
run:29, ThreadLocalResettingRunnable (org.jboss.threads)
run:30, FastThreadLocalRunnable (io.netty.util.concurrent)
run:829, Thread (java.lang)
```

**Comment by lppedd** [comment]
Ok, well, it seems like it doesn like the `git cherry-pick -to "my-branc" h"` part in the reply.
It tries to parse it every time, even if I don't prepend the command with `@bot`.

**Comment by gsmet** [comment]
Yeah. Because of https://github.com/quarkiverse/quarkus-github-app/blob/main/command-airline/runtime/src/main/java/io/quarkiverse/githubapp/command/airline/runtime/AbstractCommandDispatcher.java#L73 .

This needs to be changed. It wasn't coded like that before and I switched to something cuter but it's more brittle.

**Comment by lppedd** [comment]
@gsmet well that's good that you know where the change should be 😄 
Do you want me to provide something else or am I done for now?

**Comment by gsmet** [comment]
No, I'll fix it. Should be easy enough.

**Comment by gsmet** [comment]
@lppedd 1.13.0 has hit Maven Central with this fix and a few other improvements.
