### ISSUE TITLE
Works only with Jakarta ?

### ISSUE THREAD

**Issue by MathieuSoysal** [quarkiverse/quarkus-github-app#437]
## Introduction

Currently, I'm trying to use *quarkus-github-app* with GitHub Codespace.
My GitHub Repo is [here](https://github.com/MathieuSoysal/Template-Simplifier)
My GitHub Codespace (the dev environment) is [here](https://github.com/codespaces/new?hide_repo_select=true&ref=main&repo=600763176)

## Problem

When I execute the command `.mnvw quarkus:dev` I obtain always this error:
```log
@MathieuSoysal ➜ /workspaces/Template-Simplifier (main) $ ./mvnw quarkus:dev
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------< io.github.mathieusoysal:template-guider >---------------
[INFO] Building template-guider 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- quarkus-maven-plugin:2.16.2.Final:dev (default-cli) @ template-guider ---
[INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:2.6:resources @ template-guider
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Invoking io.quarkus.platform:quarkus-maven-plugin:2.16.2.Final:generate-code @ template-guider
[INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile @ template-guider
[INFO] Nothing to compile - all classes are up to date
[INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:2.6:testResources @ template-guider
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /workspaces/Template-Simplifier/src/test/resources
[INFO] Invoking io.quarkus.platform:quarkus-maven-plugin:2.16.2.Final:generate-code-tests @ template-guider
[INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.10.1:testCompile @ template-guider
[INFO] No sources to compile
Listening for transport dt_socket at address: 5005
2023-02-12 16:40:01,596 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2023-02-12 16:40:02,075 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.NoClassDefFoundError: jakarta/enterprise/event/Event
        at io.quarkiverse.githubapp.deployment.GitHubAppProcessor.<clinit>(GitHubAppProcessor.java:123)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at io.quarkus.deployment.util.ServiceUtil.classesNamedIn(ServiceUtil.java:29)
        at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:215)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:107)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:331)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:86)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:447)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:59)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:149)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:104)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: java.lang.ClassNotFoundException: jakarta.enterprise.event.Event
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:516)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:466)
        ... 16 more
```
### Question

Does someone know how we can fix this?

**Comment by gsmet** [comment]
Sorry I was on PTO yesterday.

`2.0.0.Alpha1` is targeting Quarkus 3. For Quarkus 2.x, use `1.16.0`. They have the exact same features.
