### ISSUE TITLE
Version 2.0.5 shows WARNING message in native

### ISSUE THREAD

**Issue by The-Huginn** [quarkiverse/quarkus-github-app#503]
Using native there is a WARNING message displayed, which is present in version 2.0.5 but not in 2.0.0

Here is the stacktrace:
```
2023-08-15 06:14:38,803 WARNING [com.git.ben.caf.cac.LocalLoadingCache] (main) Cannot determine if CacheLoader can bulk load: java.lang.NoSuchMethodException: io.quarkiverse.githubapp.runtime.github.GitHubService$CreateInstallationToken.loadAll(java.util.Set)
	at java.base@17.0.8/java.lang.Class.checkMethod(DynamicHub.java:1038)
	at java.base@17.0.8/java.lang.Class.getMethod(DynamicHub.java:1023)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.hasLoadAll(LocalLoadingCache.java:220)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.newBulkMappingFunction(LocalLoadingCache.java:198)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache.<init>(BoundedLocalCache.java:4436)
	at com.github.benmanes.caffeine.cache.Caffeine.build(Caffeine.java:1076)
	at io.quarkiverse.githubapp.runtime.github.GitHubService.<init>(GitHubService.java:69)
	at io.quarkiverse.githubapp.runtime.github.GitHubService_Bean.doCreate(Unknown Source)
	at io.quarkiverse.githubapp.runtime.github.GitHubService_Bean.create(Unknown Source)
	at io.quarkiverse.githubapp.runtime.github.GitHubService_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
	at io.quarkiverse.githubapp.runtime.github.GitHubService_ClientProxy.arc$delegate(Unknown Source)
	at io.quarkiverse.githubapp.runtime.github.GitHubService_ClientProxy.getApplicationClient(Unknown Source)
	at io.xstefank.wildfly.bot.LifecycleProcessor.onStart(LifecycleProcessor.java:73)
	at io.xstefank.wildfly.bot.LifecycleProcessor_Observer_onStart_175afe88331b177e391525f2c82e29ae610f722a.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:346)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:328)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:82)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:155)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:106)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
```

**Comment by The-Huginn** [comment]
Just to add it starts from version `2.0.4` and probably caused by bump in `caffeine.version` in quarkus from `3.1.1` to `3.1.5` [see](https://github.com/quarkusio/quarkus/commit/5e95616aba6ce8410ba69051e4e0d8a3d0d022930

**Comment by gsmet** [comment]
Thanks for the report, I thought I had solved it with 2.0.5 but actually not :).

I will release a 2.1.0 with the fix and the update to the latest GitHub API.

**Comment by gsmet** [comment]
@The-Huginn 2.1.0 is available with the fix.

**Comment by The-Huginn** [comment]
Thanks @gsmet
